#!/bin/bash
#rnmsk: renames the specified file to the snake-case file naming convention
#Created on  6 December 2019

######CONSTANTS

#####FUNCTIONS

usage() {
	echo "rnmsk: renames the specified file to the snake-case file naming convention"
	echo -e "\nUsage: rnmsk [FILE]"
}

clean_up() {
	exit 0
}

######MAIN

trap clean_up SIGINT SIGTERM SIGHUP

case "$1" in
	"--help")
					usage 
					exit 0
					;;
esac

if [ -z "$1" ]; then
	echo "please specify file name"
	exit 1
fi

if [ ! -e "$1" ]; then
	echo "file $1 does not exist"
	exit 1
fi


mv "$1" "$(echo $1 | sed 's/ //g' | sed  -e 's/\([A-Z][a-z]\)/_\L\1/g' | sed 's/\([A-Z]\)/\L\1/g' | sed 's/ //g' | sed 's/_//')"
