#!/bin/bash
#lessall: less all CAS & Symplified processes

######CONSTANTS

TMP_RC="/tmp/lessrc"
GIT_ROOT="${HOME}/git"
LESS_ALIASES="${GIT_ROOT}/tango/BuildTools/LinuxMint/bin/.alias"

# names assigned to the tabs of the services
BE_DISP="less-be"
FE_DISP="less-fe"
AD_DISP="less-ad"
CO_DISP="less-co"
CARMA_DISP="less-carma"
SYM_DISP="less-symplified"
SYM_TC_DISP="less-sym_tomcat"

declare -A LESS_CMDS
LESS_CMDS[$BE_DISP]="less_be"
LESS_CMDS[$FE_DISP]="less_fe"
LESS_CMDS[$AD_DISP]="less_ad"
LESS_CMDS[$CO_DISP]="less_co"
LESS_CMDS[$SYM_DISP]="less_sy"
LESS_CMDS[$SYM_TC_DISP]="less_st"
# TODO: figure out how to handle carma pods
#LESS_CMDS[$CARMA_DISP]="less_ca"

SYM_LOGS=("$AD_DISP" "$CO_DISP" "$SYM_DISP" "$SYM_TC_DISP")
NGX_LOGS=("$BE_DISP" "$FE_DISP")

#####FUNCTIONS

usage() {
  echo "lessall: less all CAS & Symplified processes"
  echo -e "\nUsage: lessall [POD_NAME]"
  echo -e "\n\tPOD_NAME: (optional) the shorthand name of the karma pod (e.g. gp3). If POD_NAME is not provided, then localhost is assumed"
}

clean_up() {
  rm $TMP_RC
}

######MAIN

trap clean_up SIGINT SIGTERM SIGHUP

case "$1" in
  "--help")
    usage 
    exit 0
    ;;
esac

term_args="gnome-terminal --maximize"
#term_args="xfce4-terminal"
for tabname in ${!LESS_CMDS[*]}; do
  cat > "$TMP_RC" <<- EOF
    source ${HOME}/.bashrc $LESS_ALIASES
    
    less_sy() {
      if [ -z "\$1" ]; then
        lesssy;
      else
        ssh_ad \$1 sudo -u ssouser bash -ic "less -f /var/log/symplified/symplified.log";
      fi
    }
    
    less_st() {
      if [ -z "\$1" ]; then
        lessst;
      else
        ssh_ad \$1 sudo -u ssouser bash -ic "less -f /var/log/symplified/catalina.out";
      fi
    }
EOF
  # NOTE: the less_* scripts do not account for pods on dev3-west
  region=$2
  if [[ "${SYM_LOGS[*]}" =~ "$tabname" ]] && [ ! -z "$1" ]; then
    less_arg=karma-${1}-${region:=east}-sym
  elif [[ "${NGX_LOGS[*]}" =~ "$tabname" ]] && [ ! -z "$1" ]; then
    less_arg=karma-${1}-${region:=east}-ngx
  fi
  term_args="$term_args --tab --title=$tabname -e \"bash -c 'source $TMP_RC; ${LESS_CMDS[$tabname]} $less_arg'\""
done

bash -c "$term_args" &>/dev/null

clean_up

