#!/bin/bash
#ngxlog
#Created on 10 March 2023
######CONSTANTS
#####FUNCTIONS
usage() {
	echo "ngxlog: (description)"
	echo -e "\nUsage: ngxlog"
}
clean_up() {
	exit 0
}
######MAIN
trap clean_up SIGINT SIGTERM SIGHUP
case "$1" in
	"--help")
					usage 
					exit 0
					;;
esac

if [ -z "$1" ]; then
	echo "provide the ip address of the node"
  return 1	
fi
ip_add="$1"

ssh -tt $ip_add <<- EOF
	sudo cp /var/log/rsa/securidaccess/ngx-be/ngx-be.log /home/azure-user
	sudo chmod 666 /home/azure-user/ngx-be.log 
	exit
EOF
scp ${ip_add}:/home/azure-user/ngx-be.log /tmp/ngx-be.log
vim /tmp/ngx-be.log
